# Generated by Django 5.0.7 on 2024-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employer', 'Employer'), ('Employee', 'Employee')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
