# Generated by Django 5.0.7 on 2024-07-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_favorite',
        ),
    ]
